# We have to tell the Netlify that this URL will be served by the books.js function.
[[redirects]]
  from = "/*"
  to = "https://[A-Za-z].*mangadex.com.*"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"